/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.Validacao.getSpecialCharacter;
import dao.DaoFuncionario;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sss
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    private int ini = 0;

    public FrmLogin() {
        initComponents();
        ImageIcon img = new ImageIcon("src/images/paw.png");
        this.setIconImage(img.getImage());

        txtName.setForeground(new Color(0, 15, 0));
        lblName.setForeground(new Color(156, 156, 156));
        txtPassword.setForeground(new Color(0, 15, 0));
        lblPassword.setForeground(new Color(156, 156, 156));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblExitIcon = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblLoginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FrmLogin");
        setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setBackground(new java.awt.Color(133, 151, 185));
        lblName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblName.setText("Nome:");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblName.setFocusable(false);
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 205, 30));

        lblPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblPassword.setText("Senha:");
        lblPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPassword.setFocusable(false);
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 305, 205, 30));

        txtName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtName.setBorder(null);
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 205, 30));

        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 305, 205, 30));

        btnLogin.setBackground(new java.awt.Color(25, 82, 218));
        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setMnemonic('E');
        btnLogin.setText("ENTRAR");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.setNextFocusableComponent(txtName);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 80, 40));

        lblExitIcon.setBackground(new java.awt.Color(255, 0, 0));
        lblExitIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblExitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        lblExitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitIconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitIconMouseEntered(evt);
            }
        });
        getContentPane().add(lblExitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        lblAbout.setBackground(new java.awt.Color(255, 0, 0));
        lblAbout.setForeground(new java.awt.Color(255, 255, 255));
        lblAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAboutMouseExited(evt);
            }
        });
        getContentPane().add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, -1, -1));

        lblLoginBackground.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        getContentPane().add(lblLoginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String nome = txtName.getText();
        String senha = txtPassword.getText();
        if (getSpecialCharacter(nome, senha)) {
            if (nome.length() >= 50 || senha.length() >= 50) {
                JOptionPane.showMessageDialog(null, "Não são permitidos mais de 50 caracteres", "Ops...", JOptionPane.WARNING_MESSAGE);
                txtName.setText("");
                txtPassword.setText("");
            } else {
                DaoFuncionario daoFuncionario = new DaoFuncionario();
                daoFuncionario.setNome(nome);
                daoFuncionario.setSenha(senha);
                try {
                    if (daoFuncionario.login()) {
                        FrmMain frmMain = new FrmMain();
                        frmMain.dispose();
                        frmMain.setSize(900, 600);
                        frmMain.setLocationRelativeTo(null);
                        frmMain.setResizable(false);
                        frmMain.setUndecorated(true);
                        frmMain.setVisible(true);
                        frmMain.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                        ImageIcon img = new ImageIcon("src/images/paw.png");
                        frmMain.setIconImage(img.getImage());

                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Login ou senha são inválidos, tente novamente", "Ops...", JOptionPane.WARNING_MESSAGE);
                        txtName.setText("");
                        txtPassword.setText("");
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro: \n " + ex, "Error: ", JOptionPane.ERROR_MESSAGE);
                    txtName.setText("");
                    txtPassword.setText("");
                }
            }
        } else {
            if (nome.isEmpty() || senha.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não são permitidos campos vazios", "Ops...", JOptionPane.WARNING_MESSAGE);
                txtName.setText("");
                txtPassword.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Não são permitidos caracteres especiais", "Ops...", JOptionPane.WARNING_MESSAGE);
                txtName.setText("");
                txtPassword.setText("");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setBackground(new Color(69, 30, 183));
        btnLogin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setBackground(new Color(25, 82, 218));
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnLoginMouseExited

    private void lblExitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitIconMouseClicked
        if (JOptionPane.showConfirmDialog(
                this,
                "Realmente deseja sair ?", "Atenção",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_lblExitIconMouseClicked

    private void lblExitIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitIconMouseExited
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_lblExitIconMouseExited

    private void lblExitIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitIconMouseEntered
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblExitIconMouseEntered

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        lblName.setText("");
        lblName.setVisible(false);
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if (txtName.getText().equals("")) {
            lblName.setText("Nome: ");
            lblName.setVisible(true);
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        lblPassword.setText("");
        lblPassword.setVisible(false);
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().equals("")) {
            lblPassword.setText("Senha: ");
            lblPassword.setVisible(true);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void lblAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseClicked
        this.dispose();
        FrmAbout frmAbout = new FrmAbout();
        frmAbout.dispose();
        frmAbout.setSize(900, 600);
        frmAbout.setUndecorated(true);
        frmAbout.setVisible(true);
    }//GEN-LAST:event_lblAboutMouseClicked

    private void lblAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseEntered
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblAboutMouseEntered

    private void lblAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseExited
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_lblAboutMouseExited
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblExitIcon;
    private javax.swing.JLabel lblLoginBackground;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void FrmLoginErro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
